name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Pobierz kod
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalacja
        run: npm install

      - name: Build
        run: npm run build

      - name: Tworzenie EXE
        run: npm run dist

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: ProStudio
          path: dist/
